# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 025e77b6f159908cb364141954fa839d4535d351ebf27564d27a1c2ee560a1228896f5877e715c19a2de7ebd9452ba89e25d4b5ca10becebbcc181fb98541863

test:
  secret_key_base: ec9158d88549c48c5f5dea9fd77500a3861cba23d430785c39a40e63d43b7c2b55753941953585b2d2356a72c3b789d940cd320772c18b98d1b5a97ed3e4eebc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
